---
- name: Update APT package index
  apt:
    update_cache: yes
  become: yes

- name: Upgrade system packages
  apt:
    upgrade: dist
    autoremove: yes
  become: yes

- name: Install Docker prerequisites
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release        # correct
  become: yes

- name: Add Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: Refresh APT index (after adding Docker repo)
  apt:
    update_cache: yes
  become: yes

- name: Install Docker CE, CLI, containerd and Compose v2
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  become: yes

- name: Make sure /opt/stashcloud directory is present
  file:
    path: /opt/stashcloud
    state: directory
    owner: ubuntu     
    group: ubuntu
    mode: "0755"
  become: yes

- name: Copy docker directory (docker-compose.yml + nginx.conf)
  copy:
    src: "{{ playbook_dir }}/../../docker/"
    dest: /opt/stashcloud/
    owner: ubuntu
    group: ubuntu
    mode: "0644"
  become: yes

- name: Stop and remove stashcloud frontend stack if it already exists
  community.docker.docker_compose_v2:
    project_src: /opt/stashcloud
    state: absent
  become: true
  ignore_errors: true

- name: Deploy/Update nginx and filestash
  community.docker.docker_compose_v2:
    project_src: /opt/stashcloud
    pull: always                  
    state: present
  become: yes
