plugin: amazon.aws.aws_ec2
regions:
  - eu-west-3

hostvars_prefix: ec2_

filters:
  instance-state-name: running
  tag:Project: stashcloud

hostnames:
  - tag:Name

compose:
  ansible_host: ec2_public_ip_address

groups:
  frontend: ec2_tags.Stack == 'frontend'
  backend:  ec2_tags.Stack == 'backend'

